version: 2
jobs:
  build:
    docker:
      - image: rtkaczyk/mantis-circleci:v2
    steps:
      - checkout

      - restore_cache:
          key: mantis-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}

      - run:
          name: scalastyle
          command: sbt scalastyle test:scalastyle

      - run:
          name: unit tests
          command: sbt coverage test

      - run:
          name: EVM tests
          # coverage ???
          command: sbt coverage evm:test

      - run:
          name: integration tests
          command: sbt coverageOff it:test

      - run:
          name: coverage report
          command: |
            sbt coverageReport coverageAggregate coveralls
            mkdir -p $CIRCLE_ARTIFACTS/scala-2.12
            mv target/scala-2.12/coverage-report  $CIRCLE_ARTIFACTS/scala-2.12/coverage-report
            mv target/scala-2.12/scoverage-report $CIRCLE_ARTIFACTS/scala-2.12/scoverage-report

      - run:
          name: ETS
          command: ./test-ets.sh
          no_output_timeout: 1h

      - run:
          name: additional compilation & dist
          # this step builds parts of the codebase which are not tested in CI
          # so as to prevent compilation regression
          command: sbt benchmark:compile snappy:compile dist

      - save_cache:
          key: mantis-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.m2


  full_ETS:
    docker:
      - image: rtkaczyk/mantis-circleci
    steps:
      - checkout

      - restore_cache:
          key: mantis-{{ checksum "build.sbt" }}

      - run:
          name: FULL ETS
          command: RUN_FULL_ETS=yes; ./test-ets.sh
          no_output_timeout: 1h


workflows:
  version: 2

  on_push:
    jobs:
      - build

  weekly_with_full_ETS:
    triggers:
      - schedule:
          cron: "0 17 * * 4"
          filters:
            branches:
              only: phase/release1_1

    jobs:
      - full_ETS
